### ISSUE TITLE
Modals are off screen when text is too long

### ISSUE THREAD

**Issue by daniel-dia** [creativetimofficial/ct-light-bootstrap-dashboard-pro#40]
When a modal with a big text appears, then it goes off the screen (to the bottom os screen)
I fixed it by removing the fallowing rules from my CSS
```
.modal.show .modal-dialog {
    -webkit-transform: translate(0, 30%);
    -o-transform: translate(0, 30%);
    transform: translate(0, 30%);
}
```

**Comment by alexandru-paduraru** [comment]
@artsjedi thank you for letting us know, we will fix it in the next update.
