### ISSUE TITLE
Want at least 2 sub-level menus in the sidebar

### ISSUE THREAD

**Issue by ksa689** [creativetimofficial/ct-light-bootstrap-dashboard-pro#41]
Hi everyone, I would like to have 1 or 2 sub-level menus more in the sidebar. As I am not very familiar with javascript, may someone suggest some code to provide this functionality in light-boostrap-dashboard-pro 
 ? I am looking for something like the left sidebar in this template :   
https://modularcode.io/modular-admin-html/

**Comment by groovemen** [comment]
Hi ksa689,
You don't have to use JavaScript to make the sidebar with two sub-level menus. Just make another `collapse` inside of the collapse and set the `nav-item` the collapse trigger.

Best,
Stefan

**Comment by ksa689** [comment]
Hi Stefan,
thanks for your reply.

1/ However, I have not succeeded as I would like. Here is the html code to
try to insert a 2nd level submenu.

*     *
     <li class="nav-item">
         <a class="nav-link" href="./components/buttons.html">
           <span class="sidebar-mini">  <i class="fa fa-circle-o"></i>
 </span>
           <span class="sidebar-normal">Buttons</span>
         </a>
     </li>
*     *
     <li class="nav-item">
<a class="nav-link" data-toggle="collapse" href="#SubMenuLevel2_01">
<i class="nc-icon nc-app"></i>
<p>
        Sub-Components
<b class="caret"></b>
</p>
</a>
<div class="collapse" id="SubMenuLevel2_01">
   <ul class="nav">
<li class="nav-item">
<a class="nav-link" href="#">
<span class="sidebar-mini">A1</span>
<span class="sidebar-normal">action1</span>
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="#">
<span class="sidebar-mini">A2</span>
<span class="sidebar-normal">action2</span>
</a>
</li>
   </ul>
</div>
      </li>

*The problem :*
- when the submenu expand, all the child items are highlighted

2/* Also, I would like an update to allow those features regarding this
left sidebar menu :*

a) within a menu, all children are indented a little bit toward the right
direction
b) when I use Font Awesome Icons (eg: <i class="fa fa-circle-o"> ), the
icon appear too big
c) most important : when I clicked on a submenu item, I would like the
submenu to remain expanded and highlighted, and also the clicked item
highlighted. By now, when a particular page is displayed, the sidebar is
collapsed so the menu context is lost.
Please see the attached screenshot about what I would like. You can try
also this link :
  https://modularcode.io/modular-admin-html/cards.html

I have attached here a working sample html code and the css code from the
"modular-admin-html". In this code, the desired effect is provided with 2
class names : the class name "in" in the <ul> tag keep the menu expanded
and highlighted, and the class name "active" in the <li> tag keep the menu
item highlighted.
I have customized the code only to include the Font Awesome Icon in the
left of each submenu item. See the attached "sample1.jpg"
I have the css and javascript code of the "modular-admin-html", but I do
not know how to adapt those codes in licenced
"light-bootstrap-dashboard-pro".

regards,

Kelly



2017-12-19 23:49 GMT-10:00 Stefan <notifications@github.com>:

**Comment by groovemen** [comment]
Hello again,

you can use this code inside of the <nav> from the Components items:
```
<li class="nav-item ">
  <a class="nav-link" data-toggle="collapse" href="#componentsCollapse">
    <span class="sidebar-mini"> MLT </span>
    <span class="sidebar-normal"> Multi Level Collapse
      <b class="caret"></b>
    </span>
  </a>
  <div class="collapse" id="componentsCollapse">
    <ul class="nav">
      <li class="nav-item ">
        <a class="nav-link" href="#0">
          <span class="sidebar-mini"> E </span>
          <span class="sidebar-normal"> Example </span>
        </a>
      </li>
    </ul>
  </div>
</li>
```

and it will look like this: 
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/21063398/45681078-4932be80-bb45-11e8-88f9-b8ee9e875289.gif)

Best, 
Stefan
