### ISSUE TITLE
Button Disable should not have transparent background

### ISSUE THREAD

**Issue by hbinduni** [creativetimofficial/ct-light-bootstrap-dashboard-pro#42]
Hi, i check, when i set button state to disabled, it has transparent background, so in login page example, i can not read the button title. Also label with class error, not in red color. Please fixed it.

<img width="369" alt="screenshot 2017-12-21 22 08 39" src="https://user-images.githubusercontent.com/1378410/34261376-8ec0ce44-e69b-11e7-8690-1667e953e87f.png">

**Comment by groovemen** [comment]
Hi @hbinduni, thank you for using our product! 
The `disabled` state is overwritten by another style, so please set the following style for the submit button:
` background-color: #ffc107;`
` border-color: #ffc107;`
` opacity: .5; `

Thank you!
Best, Stefan
