### ISSUE TITLE
Issues with dropdown in modal

### ISSUE THREAD

**Issue by nguyenlnc** [creativetimofficial/ct-light-bootstrap-dashboard-pro#46]
I'm using "Customizable Select" for bootrap-modal. But it did not work. Please help me check

![image](https://user-images.githubusercontent.com/24447765/35133199-75367d76-fd01-11e7-9865-e9186c10a974.png)

Could not show the list option.

**Comment by dragosct10** [comment]
Hi, @nguyenlnc! Please can you give the link of your project to see exactly what happened? 

Regards,
Dragos
