### ISSUE TITLE
Bug in SCSS files

### ISSUE THREAD

**Issue by sakibulalam** [creativetimofficial/ct-light-bootstrap-dashboard-pro#47]
***Version***  2.0.1

I think there is a bug/syntax error with the `$sidebar-width` variable in the `SCSS` files `_sidebar-and-main-panel.scss` (line 445) and `_navbars.scss` (line 171).

The `$sidebar-width` variable is not processed and ends up verbatim in the `CSS` output. It should be written as `#{$sidebar-width}`.

**Comment by groovemen** [comment]
Hello @sakibulalam, thank you for using our product!
 We checked the issue and it looks like it works fine. You can see in the photos below. If the problem persists please send to us a link to your project. 

Best, Stefan

// Variables file
<img width="547" alt="screen shot 2018-02-09 at 10 31 56" src="https://user-images.githubusercontent.com/21063398/36018613-080ad690-0d85-11e8-879e-eed5f8047445.png">
// SASS file
<img width="397" alt="screen shot 2018-02-09 at 10 32 13" src="https://user-images.githubusercontent.com/21063398/36018614-08242f1e-0d85-11e8-923d-d20dfaac9100.png">
// CSS file
<img width="430" alt="screen shot 2018-02-09 at 10 32 41" src="https://user-images.githubusercontent.com/21063398/36018615-08421c86-0d85-11e8-9e4f-907a4c4a6805.png">
