### ISSUE TITLE
Sweet Alert 2 - Error animation

### ISSUE THREAD

**Issue by FinnJanik** [creativetimofficial/ct-light-bootstrap-dashboard-pro#51]
The Sweet Alert 2 error type animation doesn't work. You can see the red circle, but the cross is not displayed. Test it yourself: http://demos.creative-tim.com/light-bootstrap-dashboard-pro/examples/components/sweet-alert.html

**Comment by groovemen** [comment]
Hello @FinnJanik, 

Thank you for using our products, I checked the issue and also solve it. I will ask you to make the following changes:
- set background-color: #fa8b87; for both lines;  - you can see in the image below
<img width="1315" alt="screen shot 2018-09-17 at 23 46 17" src="https://user-images.githubusercontent.com/21063398/45649521-3338e580-bad4-11e8-96ff-32abd1ad52ac.png">

Best, 
Stefan
