### ISSUE TITLE
Tab Content with Bootstrap Tables

### ISSUE THREAD

**Issue by janmeetsingh** [creativetimofficial/ct-light-bootstrap-dashboard-pro#57]
I have bootstrap tables placed inside tab content, there are three tabs and each contains different tables.
Tabs otherwise work fine, but when bootstrap tables are placed inside tabs break and doesn't work. One or the other tab remains open. [Click here](http://connectmd.in/doctor_referral/my-referrals.php) to check the issue. Default tab will load just fine, click on 2nd tab then 3rd, content of the 2nd tab will still be there.

**Comment by groovemen** [comment]
Hello @janmeetsingh, thank you for using our products, I checked for the issue but it looks good. When I change the tabs, the content changes with different tables. Did you fix this problem ?
All the best, Stefan
