### ISSUE TITLE
Bootstrap Wizard Back-Button doesn't work

### ISSUE THREAD

**Issue by CodingAnonymous** [creativetimofficial/ct-light-bootstrap-dashboard-pro#60]
Hello,

the Back-Button in the Bootstrap-Wizard doesn't work. When I click on it nothing happens (the tab doesn't go back). How can I activate or fix it?

Thanks!

**Comment by groovemen** [comment]
Hello @CodingAnonymous,

Thank you for using our products and sorry for the late response, all you have to do is to change the class `.btn-back` to `.btn-previous` from the wizzard. Also, I see that you have to set extra property:     `border: none;` to that button on the first tab.

Hope this information helps you.
All the best,
Stefan

**Comment by lactasoy-cs** [comment]
property: border: none;
where to edit
