### ISSUE TITLE
Table row extends past card

### ISSUE THREAD

**Issue by Joebayld** [creativetimofficial/ct-light-bootstrap-dashboard-pro#61]
Noticing that as certain zooms, the table rows extend past the card. Screenshot below. 

<img width="432" alt="image" src="https://user-images.githubusercontent.com/9399317/44380009-d1865b00-a4d6-11e8-9746-7e6339a94a33.png">

**Comment by groovemen** [comment]
Hello @Joebayld,

Thank you for using our products, I will ask you to set the following property for the action buttons:
```
@media (max-width: 991px){
     .table-with-links .td-actions .btn {
          padding: 8px 16px;
     }
}
```

** you can also add the class `table-responsive` for the table that are too big (e.g. Table Big Boy).
Best, 
Stefan
