### ISSUE TITLE
Icons not appearing on datetimepicker

### ISSUE THREAD

**Issue by cwcrawley** [creativetimofficial/ct-light-bootstrap-dashboard-pro#62]
I've copied into my application 3 datetimepickers to represent date, start time and end time. The popups work, but I cannot get the icons or styling to show correctly.

See attached images to demonstrate what I'm getting.

Any help would be much appreciated.

<img width="586" alt="screen shot 2018-08-30 at 15 15 13" src="https://user-images.githubusercontent.com/827819/44857357-8d7a1f80-ac67-11e8-8f5b-640e99bed6a0.png">
<img width="303" alt="screen shot 2018-08-30 at 15 15 07" src="https://user-images.githubusercontent.com/827819/44857358-8d7a1f80-ac67-11e8-901a-edcfc97b997d.png">

**Comment by groovemen** [comment]
Hello @cwcrawley, 

Thank you for using our products, please let us know how did you initialize the datetimepicker or can you provide us a link to your project?

All the best,
Stefan
