### ISSUE TITLE
bootstrap-table window.operateEvents works only after pagination change

### ISSUE THREAD

**Issue by bergtaucherli** [creativetimofficial/ct-light-bootstrap-dashboard-pro#67]
First of all, thank you very much for the great template :-)

But actually, I have an issue with the bootstrap table. I have implemented one click event (edit) in the table. But after loading the table, a click fires the event only after a first change of pagination. First, the application stands on page 1, a click does nothing. After I click on page 2, 3 etc. a click on the edit button works fine. 

Do you know whats wrong?

Thanks a lot for yur help :-)

`<table id="bootstrap-table" class="table table-hover table-striped">
									<thead>
										<th data-field="state" data-checkbox="true"></th>
										<th data-sortable="true" data-field="id" class="text-center">ID</th>
										<th data-sortable="true" data-field="date">Datum</th>
										<th data-field="weekday">Wochentag</th>
										<th data-field="worktime">Arbeitszeit</th>
										<th data-field="hours">Stunden</th>
										<th data-field="expenses">Spesen</th>
										<th data-field="action" class="td-actions text-center" data-events="operateEvents" data-formatter="operateFormatter">Bearbeiten</th>
									</thead>
									<tbody>
										<tr>
											<td></td>
											<td>12345</td>
											<td>18.02.2018</td>
											<td>Montag</td>
											<td>08:00 - 12:00 | 13:30 - 18:00</td>
											<td>8.50</td>
											<td>Essen: 10.00</td>
											<td></td>
										</tr>
										<tr>
											<td></td>
											<td>12346</td>
											<td>19.02.2018</td>
											<td>Dienstag</td>
											<td>08:00 - 12:00 | 13:30 - 18:00</td>
											<td>8.50</td>
											<td>Essen: 10.00</td>
											<td></td>
										</tr>
										<tr>
											<td></td>
											<td>12347</td>
											<td>20.02.2018</td>
											<td>Mittwoch</td>
											<td>08:00 - 12:00 | 13:30 - 18:00</td>
											<td>8.50</td>
											<td>Essen: 10.00</td>
											<td></td>
										</tr>
										<tr>
											<td></td>
											<td>12348</td>
											<td>21.02.2018</td>
											<td>Donnerstag</td>
											<td>08:00 - 12:00 | 13:30 - 18:00</td>
											<td>8.50</td>
											<td>Essen: 10.00</td>
											<td></td>
										</tr>
										<tr>
											<td></td>
											<td>12349</td>
											<td>22.02.2018</td>
											<td>Freitag</td>
											<td>KRANK</td>
											<td>0.00</td>
											<td></td>
										</tr>
										<tr>
											<td></td>
											<td>12350</td>
											<td>23.02.2018</td>
											<td>Samstag</td>
											<td></td>
											<td>0.00</td>
											<td></td>
											<td></td>
										</tr>
										<tr>
											<td></td>
											<td>12351</td>
											<td>24.02.2018</td>
											<td>Sonntag</td>
											<td></td>
											<td>0.00</td>
											<td></td>
											<td></td>
										</tr>
										<tr>
											<td></td>
											<td>12352</td>
											<td>25.02.2018</td>
											<td>Montag</td>
											<td></td>
											<td>0.00</td>
											<td></td>
											<td></td>
										</tr>
										<tr>
											<td></td>
											<td>12353</td>
											<td>26.02.2018</td>
											<td>Dienstag</td>
											<td></td>
											<td>0.00</td>
											<td></td>
											<td></td>
										</tr>
										<tr>
											<td></td>
											<td>12354</td>
											<td>27.02.2018</td>
											<td>Mittwoch</td>
											<td></td>
											<td>0.00</td>
											<td></td>
											<td></td>
										</tr>
										<tr>
											<td></td>
											<td>12355</td>
											<td>28.02.2018</td>
											<td>Donnerstag</td>
											<td></td>
											<td>0.00</td>
											<td></td>
											<td></td>
										</tr>
									</tbody>
								</table>`

` var $table = $('#bootstrap-table');

    $().ready(function(){
        $table.bootstrapTable({
            toolbar: ".toolbar",
            clickToSelect: true,
            showRefresh: false,
            search: false,
            showToggle: false,
            showColumns: false,
            pagination: true,
            paginationVAlign: 'both',
            searchAlign: 'left',
            pageSize: 10,
            clickToSelect: false,
            pageList: [5,10,25],

            formatShowingRows: function(pageFrom, pageTo, totalRows){
                //do nothing here, we don't want to show the text "showing x of y from..."
            },
            formatRecordsPerPage: function(pageNumber){
                return pageNumber + " Zeilen anzeigen";
            },
            icons: {
                refresh: 'fa fa-refresh',
                toggle: 'fa fa-th-list',
                columns: 'fa fa-columns',
                detailOpen: 'fa fa-plus-circle',
                detailClose: 'fa fa-minus-circle'
            }
        });

        //activate the tooltips after the data table is initialized
        $('[rel="tooltip"]').tooltip();

        $(window).resize(function () {
            $table.bootstrapTable('resetView');
        });

        window.operateEvents = {
            'click .edit': function (e, value, row, index) {
                info = JSON.stringify(row);

                swal('You click edit icon, row: ', info);
                console.log(info);
            }
        };
    });

    function operateFormatter(value, row, index) {
        return [
            '<a rel="tooltip" title="Bearbeiten" class="btn btn-link btn-icon table-action edit" href="javascript:void(0)">',
                '<i class="fa fa-edit"></i>',
            '</a>'
        ].join('');
    }`

**Comment by groovemen** [comment]
Hello @bergtaucherli,

Thank you for using our products, I have responded to you on Zendesk. 

All the best, 
Stefan

**Comment by bergtaucherli** [comment]
Hi Stefan

Thank you very much for your answer!
Great, I could resolve the issue :-)

Best regards, Martin

**Comment by WoodWhite** [comment]
> Hello @bergtaucherli,
> 
> Thank you for using our products, I have responded to you on Zendesk.
> 
> All the best,
> Stefan

Please show here, I have the same issue. thx!

**Comment by groovemen** [comment]
Hello @WoodWhite,

Thank you for using our products and sorry for not shared the info here. This is what we have sent to Martin when it opened the issue on Zendesk: 

[init Bootstrap Table.html.zip](https://github.com/creativetimofficial/ct-light-bootstrap-dashboard-pro/files/4868526/init.Bootstrap.Table.html.zip)

Please also check if you have this code from the above file on your initialization.
All the best, 
Stefan
