### ISSUE TITLE
mini sidebar opens even when not hovering over it.

### ISSUE THREAD

**Issue by goselito** [creativetimofficial/ct-light-bootstrap-dashboard-pro#70]
When the mini sidebar is set as default, it expands even when not hovering over it. This is very frustrating as it can obscure links visitors may want to click on. See attached gif
![ezgif com-crop](https://user-images.githubusercontent.com/12156784/57767746-63d82a00-770a-11e9-898b-9d294fc5ead2.gif)

**Comment by groovemen** [comment]
Hello @goselito,

Thank you for using our products and thank you for letting us know about this issue. We will fix it in the next update but until then, we'll ask you to set the following property:
```
@media (min-width: 992px)
    .sidebar-mini .sidebar, 
    .sidebar-mini .main-panel {
        overflow: hidden;
  }
```

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
