### ISSUE TITLE
No Icons

### ISSUE THREAD

**Issue by jonnyl888** [creativetimofficial/ct-light-bootstrap-dashboard-pro#72]
There seems to be no icons on the sidebar, where can I find them as they are not in assets folder.
![no icons](https://user-images.githubusercontent.com/51249909/58739352-ba7b7e80-8401-11e9-8fec-302203b75dc4.JPG)

**Comment by groovemen** [comment]
Hello @jonnyl888,

Thank you for your interest in working with our products.
It seems that you haven't respected our ISSUE_TEMPLATE, so we are going to close it.
Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well.

All the best,
Stefan
