### ISSUE TITLE
Your Light Admin Bootstrap Version

### ISSUE THREAD

**Issue by trentramseyer** [creativetimofficial/ct-light-bootstrap-dashboard-pro#74]
Downloaded and it was 3.x

The demo still says 4-BETA
https://demos.creative-tim.com/light-bootstrap-dashboard/assets/css/bootstrap.min.css

Any chance you plan to get these with 2019?

**Comment by groovemen** [comment]
Hello @trentramseyer,

Thank you for using our products, unfortunately, we are very busy with the development of new products for [creative-tim.com ](https://creative-tim.com/). I will talk with the board and probably in the near future, we will make an update. Sorry for the inconvenience.

Best, Stefan
