### ISSUE TITLE
Form Check Radio and Checkbox required not working 

### ISSUE THREAD

**Issue by spn1891** [creativetimofficial/ct-light-bootstrap-dashboard-pro#75]
Form Check Radio and Checkbox required not working after submit.

**Comment by groovemen** [comment]
Hello @spn1891,

Thank you for your interest in working with our products.
It seems that you haven't respected our ISSUE_TEMPLATE, so we are going to close it.
Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well.

All the best,
Stefan

**Comment by spn1891** [comment]
Hello,

I have bought light-bootstrap-dashboard-pro couple of months ago.
I have issue with checkbox and radio button.

When I make require filed true for both radio button and check box it allow me submit ignoring require field.
Can  you please assist.
<div class="row">
                                                    <label class="col-sm-2 control-label">Checkboxes and radios</label>
                                                    <div class="col-sm-10">
                                                        <div class="form-check">
                                                            <label class="form-check-label">
                                                                <input class="form-check-input" type="checkbox" value="" required="">
                                                                <span class="form-check-sign"></span>
                                                                First Checkbox
                                                            </label>
                                                        </div>
                                                        <div class="form-check">
                                                            <label class="form-check-label">
                                                                <input class="form-check-input" type="checkbox" value="" required="">
                                                                <span class="form-check-sign"></span>
                                                                Second Checkbox
                                                            </label>
                                                        </div>
                                                        <div class="form-check form-check-radio">
                                                            <label class="form-check-label">
                                                                <input class="form-check-input" type="radio" name="exampleRadio" id="exampleRadios1" value="option1" required="">
                                                                <span class="form-check-sign"></span>
                                                                Radio is off
                                                            </label>
                                                        </div>
                                                        <div class="form-check form-check-radio">
                                                            <label class="form-check-label">
                                                                <input class="form-check-input" type="radio" name="exampleRadio" id="exampleRadios2" value="option2" required="">
                                                                <span class="form-check-sign"></span>
                                                                Radio is on
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <button type="submit">send</button>



Regards.

Sapan Patel
IT Administrator/ Web Developer


[Singer Logo]

16 Edinburgh Street, Newton  |  PO Box 816, Shortland St, Auckland 1140
Phone 09 220 5168 | Mob 022 167 4189  | Email s.patel@singer.co.nz<mailto:s.patel@singer.co.nz>

SINCE 1953 www.singergroup.co.nz<http://www.singergroup.co.nz/>

P Please protect the environment - don't print this e-mail unless you really need to

**Comment by groovemen** [comment]
Hello again, 

Thank you for using our products, here is an example of validating a checkbox:

```
<form onsubmit="return checkForm(this);">
<p><input id="field_terms" onchange="this.setCustomValidity(validity.valueMissing ? 'Please indicate that you accept the Terms and Conditions' : '');" type="checkbox" required name="terms"> I accept the <u>Terms and Conditions</u></p>
<p><input type="submit"></p>
</form>

<script>
  document.getElementById("field_terms").setCustomValidity("Please indicate that you accept the Terms and Conditions");
</script>
```

Hope that information helps you. Please let us know if we can help you with anything else.
All the best, 
Stefan

**Comment by spn1891** [comment]
Hello Stefan,

Thank you for your response really appreciated,

But I want to use light-bootstrap-dashboard-pro check box and radio button.
Normal checkbox and bootstrap checkbox are working fine.

[cid:image002.png@01D56874.27BDE8B0]


<!DOCTYPE html>
<html>
<head>
                <title></title>
                <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
                <link href="assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="assets/css/light-bootstrap-dashboard.css?v=2.0.1" rel="stylesheet" />
</head>
<body>

<form onsubmit="return checkForm(this);">
<div class="row">
    <label class="col-sm-2 control-label">Checkboxes and radios</label>
    <div class="col-sm-10">
        <div class="form-check">
            <label class="form-check-label">
                <input class="form-check-input" id="field_terms" onchange="this.setCustomValidity(validity.valueMissing ? 'Please indicate that you accept the Terms and Conditions' : '');" type="checkbox" required name="terms">
                <span class="form-check-sign"></span>
                First Checkbox
            </label>
        </div>
    </div>
    <input type="submit">
</div>
</form>

<script>
  document.getElementById("field_terms").setCustomValidity("Please indicate that you accept the Terms and Conditions");
</script>

</body>
<script src="assets/js/core/jquery.3.2.1.min.js" type="text/javascript"></script>
<script src="assets/js/core/popper.min.js" type="text/javascript"></script>
<script src="assets/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="assets/js/light-bootstrap-dashboard.js?v=2.0.1" type="text/javascript"></script>
</html>


Regards.

Sapan Patel
