### ISSUE TITLE
[Feature Request] Bootstrap version outdated

### ISSUE THREAD

**Issue by joseph-ar** [creativetimofficial/ct-light-bootstrap-dashboard-pro#82]
### What is your enhancement?
This template is simply amazing, but I’m having several problems when trying to use it with stable versions of laravel 9 or newer, that’s because it’s uses bootstrap 5 by default; but I could change it to a previous version (4.6).

if you could update the template to Bootstrap 4.6 that’s will be so useful 👍🏻.
I’m having problems to install bootstrap 4.0.0 beta with laravel and vite

**Comment by groovemen** [comment]
Hello @joseph-ar,

Thank you for using our products, and sorry to hear that.
The only way to update the Bootstrap version into your project, is to update it manually by importing the new files and then to update the classes in your code.
We have a cheat sheet that will help you to do this work easier.

Hope this information helps you. Please let us know if we can help you with anything else.
All the best,
Stefan
